### ISSUE TITLE
Can't select metadata result when there is only one item in the list

### ISSUE THREAD

**Issue by maxwelllincoln** [utls/django-nanosourcer#1]
There was some problematic behavior for period selection – when there is only one period (“Middle Minoan”) in results set, selecting it does not immediately cause the selected URI to appear in the section header. It worked on a second or third try, but for the students we'll need it to work the first time, or they'll get frustrated.

**Comment by atomrab** [comment]
Update on this: it's not only when there's one item on the list. It is in all cases when you have NOT used the free-text search. If you have results from a map filter alone, no action is taken when you select one of them. Only after you've entered a text search term is your selection recorded.
