### ISSUE TITLE
Site "Phaistos" does not appear in search results for Crete

### ISSUE THREAD

**Issue by atomrab** [utls/django-nanosourcer#6]
A number of Battle's photos were taken at the site of Phaistos on Crete (https://pleiades.stoa.org/places/589987). But no Pleiades entry for that site comes up in search. Is that an issue of the ranking algorithm? If so, we need to address it for this dataset. It wouldn't have come up in the metadata generation, because I don't think Rio recognized it as Phaistos, and the photos weren't labeled.

**Comment by maxwelllincoln** [comment]
Added a query parameter to the GLS API to facilitate searching across the entire Pleiades URI corpus.

For instance: `.../v1/gazetteers/1/search?advanced=true&query=crete&limit=1&offset=26` would return:

``` json
{
  "response": {
    "items": [
      {
        "dateMax": 640,
        "secondaryLabel": "An ancient settlement on Crete where occupation began ca. 3000 BC, Phaistos was a major center of the Minoan civilization and continued to be a Greek city of the first millennium BC.",
        "gazetteerURI": "http://pleiades.stoa.org/places/589987",
        "long": 24.8141725,
        "dateMin": -4000,
        "relevance": 8.84846019744873,
        "spatialLabel": "Phaistos/Ag. Ioannis",
        "lat": 35.0511785,
        "label": "Phaistos"
      }
    ],
    "queryMetadata": {
      "count": 40,
      "limit": 1,
      "offset": 26
    }
  }
}
```

I am still working on adding the advanced search affordance into the UI though.
